import { config } from '@/shared/config/index.js';
import { type FirebaseAuthContext } from '@/shared/middleware/firebaseAuth.js';

/**
 * Derives the email to use for PDS account creation.
 *
 * Priority:
 *   1. Real email from the Firebase token (email/Google/Apple-with-shared-email)
 *   2. Synthetic email derived from the phone number (phone-only signups)
 *   3. Synthetic email derived from the Firebase UID (anonymous fallback)
 *
 * Synthetic emails satisfy PDS's email requirement without surfacing them to
 * the user. They live under SYNTHETIC_EMAIL_DOMAIN (default `email.fuzex.social`).
 *
 * @param authCtx - Verified Firebase auth context.
 * @returns The email PDS should associate with the account.
 */
export function deriveEmail(authCtx: FirebaseAuthContext): string {
  if (authCtx.email !== null) {
    return authCtx.email;
  }

  if (authCtx.phoneNumber !== null) {
    const digits = authCtx.phoneNumber.replace(/[^0-9]/g, '');
    return `phone-${digits}@${config.env.SYNTHETIC_EMAIL_DOMAIN}`;
  }

  return `uid-${authCtx.uid}@${config.env.SYNTHETIC_EMAIL_DOMAIN}`;
}

/**
 * Returns true if the email was generated by {@link deriveEmail}.
 *
 * @param email - Any email string.
 * @returns True iff the address is under SYNTHETIC_EMAIL_DOMAIN.
 */
export function isSyntheticEmail(email: string): boolean {
  return email.endsWith(`@${config.env.SYNTHETIC_EMAIL_DOMAIN}`);
}
